name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        go: [1.16, 1.17, 1.18, 1.19]
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Kratos
        run: |
          cd cmd/kratos
          go build ./...
          go test ./...

      - name: HTTP
        run: |
          cd cmd/protoc-gen-go-http
          go build ./...
          go test ./...