name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  resolve-modules:
    name: resolve module
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - id: set-matrix
        run: ./hack/resolve-modules.sh
  build:
    strategy:
      matrix:
        go: [1.16, 1.17, 1.18, 1.19]
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Kratos
        run: |
          cd cmd/kratos
          go build ./...
          go test ./...

      - name: HTTP
        run: |
          cd cmd/protoc-gen-go-http
          go build ./...
          go test ./...
  test:
    name: lint module
    runs-on: ubuntu-latest
    needs: resolve-modules
    services:
      etcd:
        image: gcr.io/etcd-development/etcd:v3.5.0
        ports:
          - 2379:2379
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      consul:
        image: consul:1.12.3
        ports:
          - 8500:8500
      nacos:
        image: nacos/nacos-server:v2.1.0
        env:
          MODE: standalone
        ports:
          - "8848:8848"
          - "9848:9848"
      polaris:
        image: polarismesh/polaris-server-standalone:v1.9.0
        ports:
          - 8090:8090
          - 8091:8091
          - 8093:8093
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go }}
          working-directory: ${{ matrix.workdir }}
        run: go test ./...