name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Kratos
      run: |
        cd cmd/kratos
        go build ./...
        go test ./...

    - name: HTTP
      run: |
        cd cmd/protoc-gen-go-http
        go build ./...
        go test ./...

    - name: Errors
      run: |
        cd cmd/protoc-gen-go-errors
        go build ./...
        go test ./...
